2020-07-28 12:24:46,689 ERROR: Exception on /login [POST] [in /home/nathan/Insync/nathanfaulkner@fcds.org/Google Drive/Textbook Project/encyclopedia/venv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/nathan/Insync/nathanfaulkner@fcds.org/Google Drive/Textbook Project/encyclopedia/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nathan/Insync/nathanfaulkner@fcds.org/Google Drive/Textbook Project/encyclopedia/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nathan/Insync/nathanfaulkner@fcds.org/Google Drive/Textbook Project/encyclopedia/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nathan/Insync/nathanfaulkner@fcds.org/Google Drive/Textbook Project/encyclopedia/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/nathan/Insync/nathanfaulkner@fcds.org/Google Drive/Textbook Project/encyclopedia/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nathan/Insync/nathanfaulkner@fcds.org/Google Drive/Textbook Project/encyclopedia/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nathan/Insync/nathanfaulkner@fcds.org/Google Drive/Textbook Project/encyclopedia/app/routes.py", line 62, in login
    if user is None or not user.check_password(form.password.data):
  File "/home/nathan/Insync/nathanfaulkner@fcds.org/Google Drive/Textbook Project/encyclopedia/app/models.py", line 40, in check_password
    return check_password_hash(self.password_hash, password)
  File "/home/nathan/Insync/nathanfaulkner@fcds.org/Google Drive/Textbook Project/encyclopedia/venv/lib/python3.6/site-packages/werkzeug/security.py", line 218, in check_password_hash
    if pwhash.count("$") < 2:
AttributeError: 'NoneType' object has no attribute 'count'
2020-07-28 12:40:45,767 INFO: Encyclopedia INFO [in /home/nathan/Insync/nathanfaulkner@fcds.org/Google Drive/Textbook Project/encyclopedia/app/__init__.py:50]
2020-07-28 12:41:17,525 ERROR: Exception on /login [POST] [in /home/nathan/Insync/nathanfaulkner@fcds.org/Google Drive/Textbook Project/encyclopedia/venv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/nathan/Insync/nathanfaulkner@fcds.org/Google Drive/Textbook Project/encyclopedia/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nathan/Insync/nathanfaulkner@fcds.org/Google Drive/Textbook Project/encyclopedia/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nathan/Insync/nathanfaulkner@fcds.org/Google Drive/Textbook Project/encyclopedia/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nathan/Insync/nathanfaulkner@fcds.org/Google Drive/Textbook Project/encyclopedia/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/nathan/Insync/nathanfaulkner@fcds.org/Google Drive/Textbook Project/encyclopedia/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nathan/Insync/nathanfaulkner@fcds.org/Google Drive/Textbook Project/encyclopedia/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nathan/Insync/nathanfaulkner@fcds.org/Google Drive/Textbook Project/encyclopedia/app/routes.py", line 62, in login
    if user is None or not user.check_password(form.password.data):
  File "/home/nathan/Insync/nathanfaulkner@fcds.org/Google Drive/Textbook Project/encyclopedia/app/models.py", line 40, in check_password
    return check_password_hash(self.password_hash, password)
  File "/home/nathan/Insync/nathanfaulkner@fcds.org/Google Drive/Textbook Project/encyclopedia/venv/lib/python3.6/site-packages/werkzeug/security.py", line 218, in check_password_hash
    if pwhash.count("$") < 2:
AttributeError: 'NoneType' object has no attribute 'count'
